### ISSUE TITLE
On Linux, I don’t receive EventMouseMove unless a button is pressed

### ISSUE THREAD

**Issue by igorhub** [HumbleUI/HumbleUI#10]
I test it by inserting a `println` in `on-event` function and then moving my mouse across the window.

```
(defn on-event [window event]
  (println event)
  ;; ...
  )
```

I get lots of events like these when I press one of the buttons (or both):
```

#object[io.github.humbleui.jwm.EventMouseMove 0x45801322 EventMouseMove(_x=106, _y=712, _buttons=1, _modifiers=0)]
#object[io.github.humbleui.jwm.EventMouseMove 0x7e3d2ebd EventMouseMove(_x=161, _y=602, _buttons=2, _modifiers=0)]
#object[io.github.humbleui.jwm.EventMouseMove 0x272778ae EventMouseMove(_x=258, _y=283, _buttons=3, _modifiers=0)]
```

Not a single event with _buttons=0.

**Comment by igorhub** [comment]
I actually get `EventMouseMove` with `_buttons=0` when I press one of the useless buttons on the side of my mouse.

The problem clearly originates in one of the underlying libraries, but that’s beyond my understanding. Reporting here instead.

**Comment by tonsky** [comment]
Thanks! We have it logged in JWM https://github.com/HumbleUI/JWM/issues/146
