### ISSUE TITLE
Example app won't run (EventWindowClose)

### ISSUE THREAD

**Issue by igorhub** [HumbleUI/HumbleUI#16]
HumbleUI depends on JWM 0.3.1, which doesn't have `EventWindowClose` yet.

Example app crashes with `java.lang.ClassNotFoundException`.

**Comment by tonsky** [comment]
Yeah, sorry about that. I haven’t deployed newer JWM version yet

**Comment by tonsky** [comment]
Try master, it depends on JWM 0.3.2 now

**Comment by igorhub** [comment]
Now I have a new error. I opened a separate issue.
