### ISSUE TITLE
Example app won't run (Can't find primary screen)

### ISSUE THREAD

**Issue by igorhub** [HumbleUI/HumbleUI#17]
Example app crashes at start with `java.lang.IllegalStateException`.

I'm on Ubuntu, in case it's important.

It used to work when I tried HumbleUI the last time a few weeks back.

```
{:clojure.main/message
 "Execution error (IllegalStateException) at io.github.humbleui.jwm.App/getPrimaryScreen (App.java:110).\nCan't find primary screen\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.IllegalStateException,
  :clojure.error/line 110,
  :clojure.error/cause "Can't find primary screen",
  :clojure.error/symbol io.github.humbleui.jwm.App/getPrimaryScreen,
  :clojure.error/source "App.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.IllegalStateException,
    :message "Can't find primary screen",
    :at [io.github.humbleui.jwm.App getPrimaryScreen "App.java" 110]}],
  :trace
  [[io.github.humbleui.jwm.App getPrimaryScreen "App.java" 110]
   [io.github.humbleui.core$primary_screen invokeStatic "core.clj" 77]
   [io.github.humbleui.core$primary_screen invoke "core.clj" 76]
   [user$make_window invokeStatic "user.clj" 100]
   [user$make_window invoke "user.clj" 93]
   [user$_main invokeStatic "user.clj" 119]
   [user$_main doInvoke "user.clj" 116]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "Can't find primary screen"}}
```

**Comment by igorhub** [comment]
I was able hack around it by changing `io.github.humbleui.core/primary-screen` implementation.

Here is the result of a call to `(hui/screens)`:
```
[{:id 447,
  :primary? false,
  :bounds
  #object[io.github.humbleui.types.IRect 0xbf0b367 "IRect(_left=0, _top=0, _right=1920, _bottom=1080)"],
  :work-area
  #object[io.github.humbleui.types.IRect 0x27a87546 "IRect(_left=0, _top=0, _right=1920, _bottom=1080)"],
  :scale 1.0}]
```

**Comment by tonsky** [comment]
Interesting! It would help a lot if you can maybe debug what’s happening in https://github.com/HumbleUI/JWM/blob/a3c6e47e87646e460f69e6f37497af488badf386/linux/cc/AppX11.cc#L50-L97. I’ve created an issue for it in JWM https://github.com/HumbleUI/JWM/issues/201

**Comment by igorhub** [comment]
Last time I tried I couldn’t even build the damn thing. (Probably because of my outdated Ubuntu installation.) I think I’ll try to isolate X11-related code and build it without the rest of JWM. Let me know if you think it’s a fool’s errand.

**Comment by tonsky** [comment]
Interesting! How old of an Ubuntu do you have? I think we should be ok starting from 16, 14 is too old (outdated C++)

**Comment by igorhub** [comment]
Well, my plan to extract relevant code failed, so I finally found motivation to fix my installation and properly upgrade to 20.04. I’ve built JWM now, but can’t run the example app because "release version 16 not supported". I guess java 11 is too old for the example app, even though it's fine for JWM itself. I think I'll do some debugging tomorrow.

**Comment by tonsky** [comment]
You need java 16+ to run examples
