### ISSUE TITLE
UI Fragments

### ISSUE THREAD

**Issue by Folcon** [HumbleUI/HumbleUI#22]
So I've been laying out two different application UI views and I'm finding I'm really missing the ability to add [ui fragments](https://reactjs.org/docs/fragments.html)

They're really useful to be able to conditionally insert collections:

```clojure
(when something?
  (for [item some-coll]
    (ui/label item font fill)))
```

**Comment by tonsky** [comment]
Try using lists/sequences (not vectors), same as with hiccup I belive

**Comment by Folcon** [comment]
Ah, completely missed that =)... Thanks!

I've put together a quick PR, just to make it really obvious to people that the behaviour is there and available.

I'll close the issue here as it's no longer relevant.
