### ISSUE TITLE
Key events don't respect input methods

### ISSUE THREAD

**Issue by pangloss** [HumbleUI/HumbleUI#23]
Hi, I'm just poking around since I can see the project is really early but looks nice so far. Good work! 

I noticed that when I type in your wordle demo using the dvorak keymap, the keypresses are still recognized as querty. 

I've run into this before when using raw keyboard events rather than the higher level key events provided by the OS, but that was a totally different environment, so just mentioning it in case it helps.

**Comment by tonsky** [comment]
Thanks! My bad, JWM actually separates text from keys, I just picked the wrong one

**Comment by tonsky** [comment]
Fixed in fe5bc66076c49c0869e9513331733dadc186016b
