### ISSUE TITLE
Is it safe to dedupe `ui/gap` calls?

### ISSUE THREAD

**Issue by frenchy64** [HumbleUI/HumbleUI#36]
In the calculator example, I added a single global gap

```clojure
(def gap (ui/gap 0 padding))
```

and then replaced all `(ui/gap 0 padding)` calls with `gap`.

Some of the lines between buttons are now missing:

<img width="637" alt="Screen Shot 2022-09-05 at 12 07 04 AM" src="https://user-images.githubusercontent.com/287396/188358732-a609c3b9-063b-4ce1-b0aa-478f0135be86.png">

Is this expected? I found this while refactoring this namespace with `(interleave (ui/gap 0 padding) ...)` calls which seem to work in other examples, but not here.

**Comment by tonsky** [comment]
I haven’t think about it, but actually it might not be safe to do that with more stateful components. But I also realized I do it with the gap all the time. I guess gaps should be ok? I wonder what’s going on there

**Comment by frenchy64** [comment]
I looked more into this. My mistake, the reason the lines were deleted was because I replaced `(ui/gap 0 padding)` with `(ui/gap padding 0)`. Seems to work fine.
