### ISSUE TITLE
`(hui/doui (hui/doui ...))` freezes code.

### ISSUE THREAD

**Issue by rgkirch** [HumbleUI/HumbleUI#4]
Also, it doesn't generate any error other than freezing the code.

**Comment by rgkirch** [comment]
I'm not trying to break things. Inside `hui/doui` I called a function that called `hui/doui`.

Can I also get clarification on what this does? I start the jvm with `./script/run.py` and then I connect with cider. Why am I not on the ui thread already? JWM/App init saves the current thread id as _the_ ui thread id and I assume my repl thread is the "current thread" so I expect that my repl is on the ui thread. `(hui/doui (println "hi"))` prints in my cmd prompt where I ran run.py not my repl so my repl is not the ui thread.

**Comment by tonsky** [comment]
hui/doui schedules code to run on ui thread. Calling it second time should do nothing, so we’ll need to fix that.

The idea is that you do all App/Window operations on UI thread only. On Windows it should be the thread where App/init was called. On macOS, it’s more complicated. It should be the thread app starts on. All event callbacks also happen on UI thread.

To work on both platforms, usually do this:

- Start app by calling -main
- Run nREPL/REPL in a future
- Call App/init and App/start

App/start will block the first thread, but you’ll have your REPL in a different one.

**Comment by rgkirch** [comment]
Ooh, ok. Thanks!

**Comment by tonsky** [comment]
If you don’t mind, I’ll keep it open. I want to fix nested doui-s

**Comment by rgkirch** [comment]
Oh right, mb.
