### ISSUE TITLE
Add clj-kondo support

### ISSUE THREAD

**Issue by zerg000000** [HumbleUI/HumbleUI#47]
clj-kondo is a linter for Clojure. Adding support would make code editing a lot more comfortable.

https://github.com/clj-kondo/clj-kondo

For the library owner

https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration

#46 

The PR is mainly let clj-kondo learn how to lint the `dynamic`, `cond+`, `loopr` macro.

**Comment by tonsky** [comment]
Closed in #46
