### ISSUE TITLE
How do I use deps.edn to get an nrepl?

### ISSUE THREAD

**Issue by rgkirch** [HumbleUI/HumbleUI#5]
So far, I'm just editing user.clj and running run.py but I want to add some dependencies. How can I launch an nrepl with clj and the deps.edn config?
I tried adding something to the windows alias...
```
:aliases
 {:windows
  {:extra-deps {io.github.humbleui.skija/skija-windows {:mvn/version "0.96.0"}}
   :main-opts ["-m" "nrepl.cmdline"
               "--middleware" "[cider.nrepl/cider-middleware]"]}}
```
`clj -A:windows` gives me `WARNING: Use of :main-opts with -A is deprecated. Use -M instead.
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate nrepl/cmdline__init.class, nrepl/cmdline.clj or nrepl/cmdline.cljc on classpath.`

I feel a little guilty since this isn't related to the project.

**Comment by tonsky** [comment]
You need to add nREPL dependency too. deps.edn has it in `:nrepl` alias, so you can call:

```
clj -A:dev:windows
```

Or copy nrepl dependency to windows alias

**Comment by rgkirch** [comment]
Thanks! That seems simple now, haha.
