### ISSUE TITLE
`NixOS/Wayland` debug session: with multiple text inputs, text inputs are occasionally unfocused

### ISSUE THREAD

**Issue by jakeisnt** [HumbleUI/HumbleUI#58]
Hey! Set up HumbleUI today and tried out on my Wayland/NixOS machine.  

Had some minor issues with the Wordle game and text input: it seems that my cursor would inconsistently lose focus when multiple text inputs were visible on the screen, preventing me from continuing to type.

Here's the nix environment I used to run HumbleUI (happy to contribute/support Nix upstream!): https://github.com/jakeisnt/HumbleUI/blob/390efdf14a0351e0bc35962eb0b116fb64c29c7b/flake.nix

Here's the screencast I took of the debugging session: https://youtu.be/h7_An8ZbfZA
I tried using a program to show what keys I was pressing, but had limited success with the tiled WM (Sway).

No errors were shown in the REPL besides in that error tab.

Happy to debug further and/or supply more information! 

It also might be helpful to get some 'ground truth' video of all of the demos or other important sample applications to compare to - this seems like a much lower lift than any sort of UI testing ATM, and it would make assessing whether behavior is incorrect very easy.

**Comment by tonsky** [comment]
Yeah, I broke text focus recently and noticed it, too. Will fix

**Comment by tonsky** [comment]
Should be fixed!

**Comment by jakeisnt** [comment]
Yup! Fixed all of my problems. Thanks :  )
