### ISSUE TITLE
Crash when pressing Ctrl+Z inside a text-field

### ISSUE THREAD

**Issue by lross2k** [HumbleUI/HumbleUI#81]
## Environment

- Windows 11 x64
- Ryzen 5 3550H
- Nvidia GTX 1050 Ti
- Java(TM) SE Runtime Environment (build 20.0.2+9-78)

## How to reproduce

1. Write any character inside a text-field

![start](https://github.com/HumbleUI/HumbleUI/assets/68199340/59b44cb4-5bd2-4a4a-a440-14e1aa4acaae)
![char](https://github.com/HumbleUI/HumbleUI/assets/68199340/4923f1ff-519a-4c5d-a880-39cc1026b849)

2. Press Ctrl + Z
3. App crashes with EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb421001ac, pid=13788, tid=14972 (full log messages [hs_err_pid4740.log](https://github.com/HumbleUI/HumbleUI/files/12313767/hs_err_pid4740.log), [hs_err_pid11532.log](https://github.com/HumbleUI/HumbleUI/files/12313768/hs_err_pid11532.log), [hs_err_pid13788.log](https://github.com/HumbleUI/HumbleUI/files/12313769/hs_err_pid13788.log))

## Aditional notes

Ctrl+C and Ctrl+V don't work either, but at least they don't crash my app, thanks for your amazing project and time!

**Comment by tonsky** [comment]
This should’ve been fixed https://github.com/HumbleUI/HumbleUI/issues/80

**Comment by lross2k** [comment]
My bad, I was using an old version, already tested with #80 and the undo is working correctly

However, Ctrl+C and Ctrl+V don't seem to work, is there a way to enable it?

**Comment by tonsky** [comment]
try now?

**Comment by lross2k** [comment]
I can confirm all Ctrl+A, Ctrl+C, Ctrl+V and Ctrl+Z are now working on Windows 11, thank you very much!
