### ISSUE TITLE
Examples in README don't work

### ISSUE THREAD

**Issue by camsaul** [HumbleUI/HumbleUI#89]
```clj
(ns my.namespace 
 (:require [io.github.humbleui.ui :as ui]))

(def ui
  (ui/default-theme
   {}
   (ui/center
    (ui/label "Hello world!"))))
```

fails with 

> class clojure.lang.Delay cannot be cast to class clojure.lang.IFn

It looks like `ui/label` is a delay, not a function.

**Comment by camsaul** [comment]
After digging into the source code and examples more, these should be changed to vectors instead of function calls, right?

**Comment by tonsky** [comment]
Yep, sorry about that. I updated README
