### ISSUE TITLE
Will this ever migrate to Skiko?

### ISSUE THREAD

**Issue by nedtwigg** [HumbleUI/HumbleUI#90]
- When Skija was announced in Nov 2020 https://tonsky.me/blog/skija/
  - > **What’s with the rest of the puzzle?**
     > Both things are in the works in JetBrains.
     > - For window management/OS integration, there’s [Skiko](https://github.com/JetBrains/skiko/). It says that it is Skia for Kotlin, but it also implements window creation, events, packaging, the whole deal. It even integrates with AWT and Swing.
     > - And for UI toolkit there’s [Compose Desktop](https://github.com/JetBrains/compose-jb). It’s a fork of Android Compose, a declarative UI framework, that runs in a desktop environment.
- In Aug 2021 the Skiko project bumped its Skija version to 0.93.1
  - https://github.com/JetBrains/skiko/pull/147
- In Sep 2021 the Skiko project slurped all of Skija's code and ended the dependency link
  - https://github.com/JetBrains/skiko/pull/150

Since that time, the development pace of Skija and Skiko have both dropped off, but Skiko is currently far more active than Skija. I assume a lot of this is because JetBrains Compose engineers used to contribute to Skija, and now they contribute instead to Skiko
- https://github.com/HumbleUI/Skija/graphs/contributors
- https://github.com/JetBrains/skiko/graphs/contributors

The HumbleUI project is an *incredible* revitalization of the Java UI space, thank you *so much*. If HumbleUI were started from scratch today, would it just build itself on Skiko and let JetBrains do all the maintenance on the low-level Skia primitives? Is a there a chance that such a migration might happen sometime in the future? Or do you think that Skia is going to stay static enough that "maintenance-mode" Skija is a better a choice than Skiko?

**Comment by tonsky** [comment]
Skiko is Kotlin and I don’t want to bring Kotlin to a project that already has Clojure. Also development pace doesn’t matter that much — we have most of the features we need, and also some extras (via Skia patching) that neither Skia nor Skiko have.

**Comment by nedtwigg** [comment]
"Skia patching" means that you have added features to the Skia C++ code? Are you worried about rebasing these patches onto new versions of Skia as they come out, or do you plan to freeze Skia at the point you adopted it?

**Comment by tonsky** [comment]
See here https://github.com/HumbleUI/SkiaBuild/tree/master/patches
It’s been good so far, I remove them one-by-one as Skia fixes them. I do not plan to freeze Skia version

**Comment by nedtwigg** [comment]
Cool, I can see that these patches are minor and won't be the cause of a giant migration headache. If you (or somebody else) did decide to swap Skija for Skiko, do you anticipate that being mostly a big package regex find/replace, or do you anticipate that there would be some deeper conceptual differences that would need attention?

EDIT: sorry, didn't mean to close the issue, but this is my last question anyway, and you've been very generous with your time so no worries, I can dig in to the current API of Skija vs Skiko myself, but I am of course curious about your opinion as the originator of the whole project! Switching to Skiko would solve some problems for you such as https://github.com/HumbleUI/SkiaBuild/issues/8, but I suppose it's a minor issue

**Comment by tonsky** [comment]
Honestly no idea, depends on how far did Skiko deviated from the original Skija fork
